from losses.aesthetic_loss import AestheticLoss
from losses.classification_loss import ClassificationLoss
from losses.xing_loss import XingLoss
from losses.clip_loss import CLIPLoss
from losses.perceptual_loss import PerceptualLoss
from losses.novelty_loss import NoveltyLoss
from losses.conformal_loss import ConformalLoss
from losses.tone_loss import ToneLoss
from losses.style_loss import StyleLoss
